insert into
    game_asset(game_id, asset_type, asset_unit)
values
    (1, 'meso', 'quantity'),
    (1, 'donor point (private server)', 'quantity'),
    (1, 'equipment', 'name'),
    (1, 'account', 'name'),
    (2, 'skin', 'name'),
    (3, 'skin', 'name'),
    (4, 'town hall', 'name'),
    (4, 'gems', 'quantity'),
    (4, 'account', 'name'),
    (5, 'genesis crystal', 'quantity'),
    (5, 'account', 'name'),
    (6, 'oneiric shard', 'quantity'),
    (6, 'account', 'name'),
    (7, 'PokeCoins', 'quantity'),
    (7, 'pokemon', 'name'),
    (7, 'account', 'name'),
    (8, 'account', 'name'),
    (9, 'lunite', 'quantity'),
    (9, 'account', 'name'),
    (10, 'token', 'quantity'),
    (10, 'item', 'name'),
    (11, 'account', 'name'),
    (11, 'valorant points', 'quantity'),
    (12, 'gold', 'quantity'),
    (13, 'unknown cash', 'quantity'),
    (13, 'account', 'name'),
    (14, 'PLEX', 'quantity'),
    (14, 'ship', 'name'),
    (15, 'V-Bucks', 'quantity'),
    (15, 'skin', 'name'),
    (15, 'account', 'name');